### ISSUE TITLE
Match non-Invoke calls in TransactionResult

### ISSUE THREAD

**Issue by PearsonWhite** [NethermindEth/blockifier-tester#44]
This is the corresponding issue for the following lines of code in `src/transaction_simulator.rs`:
`impl Display for TransactionResult {`:
```            TransactionResult::DeployAccount => {
                write!(f, "TODO determine success of deploy account transactions")
            }
            TransactionResult::L1Handler => write!(f, "L1Handler transactions not handled yet"),
            TransactionResult::Declare => write!(f, "Declare transactions not handled yet"),
```
There are also cases in `block_transaction_to_broadcasted_transaction`

**Comment by PearsonWhite** [comment]
Created workaround on [pwhite/L1Handler_workaround](https://github.com/NethermindEth/blockifier-tester/tree/pwhite/L1Handler_workaround)

**Comment by rodrigo-pino** [comment]
Superseded by #59
